// Machine-readable error codes returned by API endpoints instead of
// human-readable messages. The frontend maps each code to a localized
// string under the `errors` namespace in `i18n/index.ts`
// (e.g. ErrorCodes.CATEGORY_NOT_FOUND -> errors.CATEGORY_NOT_FOUND).
export const ErrorCodes = {
  // auth
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // auth middleware
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ADMIN_ACCESS_REQUIRED: 'ADMIN_ACCESS_REQUIRED',

  // part categories
  INVALID_CATEGORY_ID: 'INVALID_CATEGORY_ID',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  INVALID_PARAMETER_ID: 'INVALID_PARAMETER_ID',
  PARAMETER_NOT_FOUND: 'PARAMETER_NOT_FOUND',
  PARAMETER_UPDATE_FAILED: 'PARAMETER_UPDATE_FAILED',
  CATEGORY_PARAMETERS_IN_USE: 'CATEGORY_PARAMETERS_IN_USE',
  CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',
  CATEGORY_HAS_PARTS: 'CATEGORY_HAS_PARTS',
  CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',

  // parts
  PART_CODE_ALREADY_EXISTS: 'PART_CODE_ALREADY_EXISTS',
  INVALID_PART_ID: 'INVALID_PART_ID',
  PART_NOT_FOUND: 'PART_NOT_FOUND',
  PART_UPDATE_FAILED: 'PART_UPDATE_FAILED',
  // Category names its parts manually ('custom' mode) but no name was given.
  PART_NAME_REQUIRED: 'PART_NAME_REQUIRED',
  PART_DELETE_FAILED: 'PART_DELETE_FAILED',
  // A project's frozen BOM still claims this part. `project_parts.part_id` has
  // no ON DELETE, so the delete is blocked at the database too — this is the
  // friendly version of that. Also raised for the sub-product whose cascade
  // would take a claimed revision with it.
  PART_IN_USE_BY_PROJECT: 'PART_IN_USE_BY_PROJECT',

  // products
  PRODUCT_SKU_ALREADY_EXISTS: 'PRODUCT_SKU_ALREADY_EXISTS',
  INVALID_PRODUCT_ID: 'INVALID_PRODUCT_ID',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_UPDATE_FAILED: 'PRODUCT_UPDATE_FAILED',
  INVALID_PRODUCT_TYPE: 'INVALID_PRODUCT_TYPE',

  // sub-products
  SUB_PRODUCT_SKU_ALREADY_EXISTS: 'SUB_PRODUCT_SKU_ALREADY_EXISTS',
  INVALID_SUB_PRODUCT_ID: 'INVALID_SUB_PRODUCT_ID',
  SUB_PRODUCT_NOT_FOUND: 'SUB_PRODUCT_NOT_FOUND',
  SUB_PRODUCT_UPDATE_FAILED: 'SUB_PRODUCT_UPDATE_FAILED',
  INVALID_SUB_PRODUCT_TYPE: 'INVALID_SUB_PRODUCT_TYPE',

  // part alternatives. No "already linked" code: POST replaces.
  PART_ALTERNATIVE_SAME_PART: 'PART_ALTERNATIVE_SAME_PART',
  PART_ALTERNATIVE_NOT_FOUND: 'PART_ALTERNATIVE_NOT_FOUND',

  // product types (Settings page)
  INVALID_PRODUCT_TYPE_ID: 'INVALID_PRODUCT_TYPE_ID',
  PRODUCT_TYPE_NOT_FOUND: 'PRODUCT_TYPE_NOT_FOUND',
  PRODUCT_TYPE_ALREADY_EXISTS: 'PRODUCT_TYPE_ALREADY_EXISTS',
  PRODUCT_TYPE_IN_USE: 'PRODUCT_TYPE_IN_USE',
  PRODUCT_TYPE_DELETE_FAILED: 'PRODUCT_TYPE_DELETE_FAILED',

  // sub-product types (Settings page)
  INVALID_SUB_PRODUCT_TYPE_ID: 'INVALID_SUB_PRODUCT_TYPE_ID',
  SUB_PRODUCT_TYPE_NOT_FOUND: 'SUB_PRODUCT_TYPE_NOT_FOUND',
  SUB_PRODUCT_TYPE_ALREADY_EXISTS: 'SUB_PRODUCT_TYPE_ALREADY_EXISTS',
  SUB_PRODUCT_TYPE_IN_USE: 'SUB_PRODUCT_TYPE_IN_USE',
  SUB_PRODUCT_TYPE_DELETE_FAILED: 'SUB_PRODUCT_TYPE_DELETE_FAILED',

  // product document types (Settings > product type document requirements)
  INVALID_PRODUCT_DOCUMENT_TYPE_ID: 'INVALID_PRODUCT_DOCUMENT_TYPE_ID',
  PRODUCT_DOCUMENT_TYPE_NOT_FOUND: 'PRODUCT_DOCUMENT_TYPE_NOT_FOUND',
  PRODUCT_DOCUMENT_TYPE_ALREADY_EXISTS: 'PRODUCT_DOCUMENT_TYPE_ALREADY_EXISTS',
  PRODUCT_DOCUMENT_TYPE_REORDER_MISMATCH: 'PRODUCT_DOCUMENT_TYPE_REORDER_MISMATCH',

  // sub-product document types (Settings > sub-product type document requirements)
  INVALID_SUB_PRODUCT_DOCUMENT_TYPE_ID: 'INVALID_SUB_PRODUCT_DOCUMENT_TYPE_ID',
  SUB_PRODUCT_DOCUMENT_TYPE_NOT_FOUND: 'SUB_PRODUCT_DOCUMENT_TYPE_NOT_FOUND',
  SUB_PRODUCT_DOCUMENT_TYPE_ALREADY_EXISTS: 'SUB_PRODUCT_DOCUMENT_TYPE_ALREADY_EXISTS',
  SUB_PRODUCT_DOCUMENT_TYPE_REORDER_MISMATCH: 'SUB_PRODUCT_DOCUMENT_TYPE_REORDER_MISMATCH',

  // document revisions (the versions a revision-mode document type holds)
  INVALID_DOCUMENT_TYPE_ID: 'INVALID_DOCUMENT_TYPE_ID',
  DOCUMENT_TYPE_NOT_FOUND: 'DOCUMENT_TYPE_NOT_FOUND',
  DOCUMENT_TYPE_NOT_REVISION_MODE: 'DOCUMENT_TYPE_NOT_REVISION_MODE',
  DOCUMENT_TYPE_REVISION_MODE_LOCKED: 'DOCUMENT_TYPE_REVISION_MODE_LOCKED',
  INVALID_DOCUMENT_REVISION_ID: 'INVALID_DOCUMENT_REVISION_ID',
  DOCUMENT_REVISION_NOT_FOUND: 'DOCUMENT_REVISION_NOT_FOUND',
  DOCUMENT_REVISION_NAME_ALREADY_EXISTS: 'DOCUMENT_REVISION_NAME_ALREADY_EXISTS',
  DOCUMENT_REVISION_PRODUCTION_CONFLICT: 'DOCUMENT_REVISION_PRODUCTION_CONFLICT',
  DOCUMENT_REVISION_TOO_MANY_FILES: 'DOCUMENT_REVISION_TOO_MANY_FILES',
  INVALID_DOCUMENT_REVISION_FILE_ID: 'INVALID_DOCUMENT_REVISION_FILE_ID',
  DOCUMENT_REVISION_FILE_NOT_FOUND: 'DOCUMENT_REVISION_FILE_NOT_FOUND',
  DOCUMENT_REVISION_FILE_MISSING: 'DOCUMENT_REVISION_FILE_MISSING',
  DOCUMENT_REVISION_FILE_TOO_LARGE: 'DOCUMENT_REVISION_FILE_TOO_LARGE',

  // revisions
  INVALID_REVISION_ID: 'INVALID_REVISION_ID',
  REVISION_NOT_FOUND: 'REVISION_NOT_FOUND',
  REVISION_UPDATE_FAILED: 'REVISION_UPDATE_FAILED',
  // Deleting a product revision: the two states a product must never be left in.
  REVISION_IS_DEFAULT: 'REVISION_IS_DEFAULT',
  REVISION_LAST_REMAINING: 'REVISION_LAST_REMAINING',
  COMPARE_INVALID_PARAMS: 'COMPARE_INVALID_PARAMS',

  // companies
  INVALID_COMPANY_ID: 'INVALID_COMPANY_ID',
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  COMPANY_ALREADY_EXISTS: 'COMPANY_ALREADY_EXISTS',
  COMPANY_DELETE_FAILED: 'COMPANY_DELETE_FAILED',

  // stock entries
  INVALID_STOCK_ENTRY_ID: 'INVALID_STOCK_ENTRY_ID',
  STOCK_ENTRY_NOT_FOUND: 'STOCK_ENTRY_NOT_FOUND',
  STOCK_ENTRY_SAVE_FAILED: 'STOCK_ENTRY_SAVE_FAILED',

  // stock removals
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  STOCK_REMOVAL_SAVE_FAILED: 'STOCK_REMOVAL_SAVE_FAILED',

  // exchange rates
  BNR_RATE_UNAVAILABLE: 'BNR_RATE_UNAVAILABLE',

  // uploads
  INVALID_UPLOAD_TARGET: 'INVALID_UPLOAD_TARGET',
  NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
  // The staged image referenced by a create/update is no longer in `_tmp` —
  // a form left open past the 24h sweep, or a resubmit of a stale payload.
  STAGED_IMAGE_MISSING: 'STAGED_IMAGE_MISSING',

  // documents
  INVALID_DOCUMENT_ID: 'INVALID_DOCUMENT_ID',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_DELETE_FAILED: 'DOCUMENT_DELETE_FAILED',
  DOCUMENT_FILE_MISSING: 'DOCUMENT_FILE_MISSING',
  // Upload named a document type that isn't defined for this entity's type.
  DOCUMENT_TYPE_MISMATCH: 'DOCUMENT_TYPE_MISMATCH',
  // File extension outside the document type's allowed list, or outside the
  // global upload allow-list.
  DOCUMENT_EXTENSION_NOT_ALLOWED: 'DOCUMENT_EXTENSION_NOT_ALLOWED',
  DOCUMENT_TOO_LARGE: 'DOCUMENT_TOO_LARGE',
  // Linking an existing file into a revision: the source document is unknown,
  // or belongs to another product / sub-product (or to the target revision
  // itself, which would just duplicate a row).
  DOCUMENT_LINK_SOURCE_NOT_FOUND: 'DOCUMENT_LINK_SOURCE_NOT_FOUND',
  // That physical file is already on this card in this revision.
  DOCUMENT_ALREADY_LINKED: 'DOCUMENT_ALREADY_LINKED',

  // projects
  INVALID_PROJECT_ID: 'INVALID_PROJECT_ID',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  // Only a draft project may be edited or deleted.
  PROJECT_NOT_EDITABLE: 'PROJECT_NOT_EDITABLE',
  PROJECT_ALREADY_STARTED: 'PROJECT_ALREADY_STARTED',
  PROJECT_NOT_STARTED: 'PROJECT_NOT_STARTED',
  PROJECT_HAS_NO_PRODUCTS: 'PROJECT_HAS_NO_PRODUCTS',
  PROJECT_HAS_NO_PARTS: 'PROJECT_HAS_NO_PARTS',
  // The pinned revision does not belong to the product it was added under.
  PRODUCT_REVISION_MISMATCH: 'PRODUCT_REVISION_MISMATCH',
  // The BOM freeze has not run, so there are no `project_parts` to act on.
  PROJECT_PARTS_NOT_FROZEN: 'PROJECT_PARTS_NOT_FROZEN',
  PROJECT_PART_NOT_FOUND: 'PROJECT_PART_NOT_FOUND',
  // `missing_qty` may never be lowered below what is already on order.
  MISSING_QTY_BELOW_ORDERED: 'MISSING_QTY_BELOW_ORDERED',

  // project offers
  OFFER_COMPANY_ALREADY_ADDED: 'OFFER_COMPANY_ALREADY_ADDED',
  // Removing a company column whose quotes back an order already placed.
  OFFER_COMPANY_IN_USE: 'OFFER_COMPANY_IN_USE',
  // Ordering a part from a company that never quoted it.
  OFFER_PRICE_MISSING: 'OFFER_PRICE_MISSING',

  // orders
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  // Ordering more than the part's outstanding `missing_qty - ordered_qty`.
  ORDER_QUANTITY_EXCEEDS_MISSING: 'ORDER_QUANTITY_EXCEEDS_MISSING',

  // generic / global error handler
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  REQUEST_FAILED: 'REQUEST_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
