// Machine-readable error codes returned by API endpoints instead of
// human-readable messages. The frontend maps each code to a localized
// string under the `errors` namespace in `i18n/index.ts`
// (e.g. ErrorCodes.CATEGORY_NOT_FOUND -> errors.CATEGORY_NOT_FOUND).
export const ErrorCodes = {
  // auth
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // auth middleware
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ADMIN_ACCESS_REQUIRED: 'ADMIN_ACCESS_REQUIRED',

  // part categories
  INVALID_CATEGORY_ID: 'INVALID_CATEGORY_ID',
  CATEGORY_NAME_REQUIRED: 'CATEGORY_NAME_REQUIRED',
  CATEGORY_DESCRIPTION_REQUIRED: 'CATEGORY_DESCRIPTION_REQUIRED',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_PARAMETERS_IN_USE: 'CATEGORY_PARAMETERS_IN_USE',
  CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',
  CATEGORY_HAS_PARTS: 'CATEGORY_HAS_PARTS',
  CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',

  // parts
  PART_CODE_ALREADY_EXISTS: 'PART_CODE_ALREADY_EXISTS',
  INVALID_PART_ID: 'INVALID_PART_ID',
  PART_NOT_FOUND: 'PART_NOT_FOUND',
  PART_UPDATE_FAILED: 'PART_UPDATE_FAILED',
  PART_DELETE_FAILED: 'PART_DELETE_FAILED',

  // products
  PRODUCT_SKU_ALREADY_EXISTS: 'PRODUCT_SKU_ALREADY_EXISTS',
  INVALID_PRODUCT_ID: 'INVALID_PRODUCT_ID',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_UPDATE_FAILED: 'PRODUCT_UPDATE_FAILED',

  // sub-products
  SUB_PRODUCT_SKU_ALREADY_EXISTS: 'SUB_PRODUCT_SKU_ALREADY_EXISTS',
  INVALID_SUB_PRODUCT_ID: 'INVALID_SUB_PRODUCT_ID',
  SUB_PRODUCT_NOT_FOUND: 'SUB_PRODUCT_NOT_FOUND',
  SUB_PRODUCT_UPDATE_FAILED: 'SUB_PRODUCT_UPDATE_FAILED',

  // revisions
  INVALID_REVISION_ID: 'INVALID_REVISION_ID',
  REVISION_NOT_FOUND: 'REVISION_NOT_FOUND',
  REVISION_UPDATE_FAILED: 'REVISION_UPDATE_FAILED',
  COMPARE_INVALID_PARAMS: 'COMPARE_INVALID_PARAMS',

  // uploads
  INVALID_UPLOAD_TARGET: 'INVALID_UPLOAD_TARGET',
  NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',

  // documents
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_DELETE_FAILED: 'DOCUMENT_DELETE_FAILED',

  // generic / global error handler
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  REQUEST_FAILED: 'REQUEST_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
