// Machine-readable error codes returned by API endpoints instead of
// human-readable messages. The frontend maps each code to a localized
// string under the `errors` namespace in `i18n/index.ts`
// (e.g. ErrorCodes.CATEGORY_NOT_FOUND -> errors.CATEGORY_NOT_FOUND).
export const ErrorCodes = {
  // auth
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // auth middleware
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ADMIN_ACCESS_REQUIRED: 'ADMIN_ACCESS_REQUIRED',

  // part categories
  INVALID_CATEGORY_ID: 'INVALID_CATEGORY_ID',
  CATEGORY_NAME_REQUIRED: 'CATEGORY_NAME_REQUIRED',
  CATEGORY_DESCRIPTION_REQUIRED: 'CATEGORY_DESCRIPTION_REQUIRED',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_PARAMETERS_IN_USE: 'CATEGORY_PARAMETERS_IN_USE',
  CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',
  CATEGORY_HAS_PARTS: 'CATEGORY_HAS_PARTS',
  CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',

  // parts
  PART_CODE_ALREADY_EXISTS: 'PART_CODE_ALREADY_EXISTS',
  INVALID_PART_ID: 'INVALID_PART_ID',
  PART_NOT_FOUND: 'PART_NOT_FOUND',
  PART_UPDATE_FAILED: 'PART_UPDATE_FAILED',
  PART_DELETE_FAILED: 'PART_DELETE_FAILED',

  // uploads
  INVALID_UPLOAD_TARGET: 'INVALID_UPLOAD_TARGET',
  NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',

  // generic / global error handler
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  REQUEST_FAILED: 'REQUEST_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
