import { useI18n } from 'vue-i18n';
import { downloadBlob } from '../utils/downloadBlob.ts';
import { useNotificationStore } from '../stores/notificationStore.ts';

// Minimal shape of the File System Access API bits used here — the DOM lib
// this project builds against does not declare them yet.
interface FileSystemWritableStream {
  write(data: Blob): Promise<void>;
  close(): Promise<void>;
  /** Discards everything written and leaves the file as it was. */
  abort(): Promise<void>;
}

interface SaveFileHandle {
  createWritable(): Promise<FileSystemWritableStream>;
  getFile(): Promise<File>;
  /** Chrome 110+ / Edge only; absent elsewhere, hence optional. */
  remove?: () => Promise<void>;
}

type ShowSaveFilePicker = (options: {
  suggestedName?: string;
  types?: { description?: string; accept: Record<string, string[]> }[];
}) => Promise<SaveFileHandle>;

function savePicker(): ShowSaveFilePicker | undefined {
  return (window as unknown as { showSaveFilePicker?: ShowSaveFilePicker })
    .showSaveFilePicker;
}

/**
 * Clean up after a failed save.
 *
 * The picker creates the file the moment the user confirms the dialog, so a
 * build that fails afterwards would otherwise leave an empty file behind.
 * Aborting first restores whatever was there before — which is why the size
 * is only checked afterwards: anything non-empty at that point is the user's
 * own pre-existing file, picked for overwrite, and must not be deleted.
 */
async function discardFailedSave(
  handle: SaveFileHandle,
  writable: FileSystemWritableStream | undefined,
): Promise<void> {
  try {
    await writable?.abort();
  } catch {
    // Already errored or closed — nothing to unwind.
  }
  try {
    if (!handle.remove) return;
    const file = await handle.getFile();
    if (file.size === 0) await handle.remove();
  } catch {
    // Best effort: an orphaned empty file is not worth a second error toast.
  }
}

/**
 * Save generated bytes to disk, letting the user choose the folder and the
 * name in the browser's own save dialog.
 *
 * Chrome and Edge open the OS save dialog; Firefox and Safari have no such
 * API, so there the file goes to the browser's download folder under
 * `fileName`. Resolves to false when the user cancels the dialog.
 */
export function useFileSave() {
  const { t } = useI18n();
  const notify = useNotificationStore();

  /**
   * `produce` is a callback rather than a ready blob for two reasons: the save
   * dialog needs transient user activation, which expires a few seconds after
   * the click, so it has to open before a slow build rather than after it —
   * and starting the build first lets it run while the user is still picking
   * a folder.
   */
  async function save(
    fileName: string,
    mimeType: string,
    produce: () => Promise<Blob>,
  ): Promise<boolean> {
    const pending = produce();
    // Nothing awaits `pending` until the dialog closes; without this, a build
    // that fails meanwhile surfaces as an unhandled rejection. The real error
    // is still handled below, where the result is awaited for real.
    pending.catch(() => {});

    // No `await` may come between here and the picker call above — it would
    // consume the click's activation and the dialog would be blocked.
    const picker = savePicker();
    let handle: SaveFileHandle | undefined;

    if (picker) {
      const extension = fileName.slice(fileName.lastIndexOf('.'));
      try {
        handle = await picker({
          suggestedName: fileName,
          types: [{ accept: { [mimeType]: [extension] } }],
        });
      } catch (err) {
        // Dismissing the dialog is a cancel, not a failure. Anything else
        // (insecure context, expired activation) falls through to the plain
        // download below rather than losing the file.
        if (err instanceof DOMException && err.name === 'AbortError') return false;
      }
    }

    let writable: FileSystemWritableStream | undefined;
    try {
      const blob = await pending;
      if (!handle) {
        downloadBlob(blob, fileName);
        return true;
      }
      writable = await handle.createWritable();
      await writable.write(blob);
      await writable.close();
      return true;
    } catch {
      if (handle) await discardFailedSave(handle, writable);
      notify.showToast(t('errors_save_failed'), 'error');
      return false;
    }
  }

  return { save };
}
